name: Deploy Manifests

on:
  push:
    branches: [develop, main]

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  setup-build-publish-deploy:
    name: Deploy Manifests
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Branch Name
        shell: bash
        run: |
          echo "GH_REPO: $GH_REPO"
          echo "GH_PR_SHA: $GH_PR_SHA"
          echo "GH_HR: $GH_HR"
          echo "GH_BR: $GH_BR"
        env:
          GH_REPO: ${{ github.repository }}
          GH_PR_SHA: ${{ github.event.pull_request.base.sha }}
          GH_HR: ${{ env.GITHUB_HEAD_REF }}
          GH_BR: ${{ env.GITHUB_BASE_REF  }}
