name: Build Client Image and Deploy to GKE

on:
  push:
    branches:
      - develop
    paths:
      - 'client/**'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  setup-build-publish-deploy:
    name: Build Client Image and Deploy to GKE
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image & Push to Docker Hub
        run: |-
          cd client && docker build -t ptavarez/client .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ptavarez/client

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - name: gcloud Setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ env.GKE_SA_KEY }}
          project_id: ${{ env.GKE_PROJECT }}
          export_default_credentials: true

      - name: GKE Cluster Connection
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ env.GKE_SA_KEY }}

      - name: Deploy
        run: |-
          kubectl apply -f infra/k8s-prod/client-depl.yaml
          kubectl rollout restart deployment client-depl
          kubectl get services -o wide
