name: deploy-tickets

on:
  push:
    branches:
      - main
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && docker build -t ptavarez/tickets .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ptavarez/tickets
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment tickets-depl
