name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/k8s/**'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy Manifests
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: gcloud Setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      - run: gcloud kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f infra/k8s
