name: Build Auth Image and Deploy to GKE

on:
  push:
    branches: [develop, main]
    paths:
      - 'auth/**'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_TAG: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'prod'}}

jobs:
  build:
    name: Run Auth Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run npm install
        run: cd auth && npm install

      - name: Run Unit Tests
        run: cd auth && npm run test:ci

  setup-build-publish-deploy:
    name: Build Auth Image and Deploy to GKE
    runs-on: ubuntu-latest
    environment: ${{  github.ref == 'refs/heads/develop' && 'development' || 'staging' }}
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image & Push to Docker Hub
        run: |-
          cd auth && docker build -t ptavarez/auth:${{  env.DOCKER_TAG }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ptavarez/auth:${{  env.DOCKER_TAG }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - name: gcloud Setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ env.GKE_SA_KEY }}
          project_id: ${{ env.GKE_PROJECT }}
          export_default_credentials: true

      - name: GKE Cluster Connection
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ env.GKE_SA_KEY }}

      - name: Deploy
        run: |-
          envsubst < infra/auth-depl.yaml.template > auth-depl.yaml
          cat auth-depl.yaml
          kubectl apply -f auth-depl.yaml
          kubectl rollout restart deployment auth-depl
          kubectl get services -o wide
